version: "3.8"

services:
  db:
    image: postgres:16
    container_name: weather_forecast_sub_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: weather_forecast_sub_app
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  postgres_data:
