http_server:
  host: localhost
  port: 8080

db:
  migrationsPath: "file://migrations"

smtp:
  host: "smtp.ukr.net"
  port: 465
  from: "weather_forecast_sub@ukr.net"
  from_name: "Weather Forecast"

email:
  templates:
    confirmation_email: "./templates/email/confirmation_email.html"
    weather_forecast: "./templates/email/weather_forecast.html"
  subjects:
    confirmation_email: "Confirm your email"
    weather_forecast: "%s weather forecast for %s city"